version: '3'

services:
  platform_ui:
    image: quay.io/ukhomeofficedigital/cop-private-workflow-tasklist:develop
    restart: on-failure
    container_name: platform_ui
    environment:
      UI_ENVIRONMENT: "LOCAL"
      UI_VERSION: "ALPHA"
      AUTH_REALM: "refdata"
      AUTH_URL: "http://keycloak:8080/keycloak/auth"
      AUTH_CLIENT_ID: "platform-ui"
      AUTH_ACCESS_ROLE: ""

networks:
  default:
    external:
      name: local_dev