apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: borders-workflow-tasklist
spec:
  replicas: {{ .TASKLIST_REPLICA_COUNT }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: borders-workflow-tasklist
      annotations:
        owner: "amin.mohammed-coleman@digital.homeoffice.gov.uk"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/pttg-cfssl-sidekick:build-6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=borders-workflow-modeler.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ss
      - name: nginx
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.0
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
        env:
        - name: PROXY_SERVICE_HOST
          value: 127.0.0.1
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: SERVER_CERT
          value: /certs/tls.pem
        - name: SERVER_KEY
          value: /certs/tls-key.pem
        - name: SSL_CIPHERS
          value: ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:AES256+EDH:!aNULL
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: PORT_IN_HOST_HEADER
          value: "FALSE"
        - name: ERROR_REDIRECT_CODES
          value: "599"
        - name: ADD_NGINX_SERVER_CFG
          value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        - name: ADD_NGINX_LOCATION_CFG
          value: |
            gzip off;
            proxy_buffer_size         128k;
            proxy_buffers             4 256k;
            proxy_busy_buffers_size   256k;
        ports:
        - name: http
          containerPort: 10080
        - name: https
          containerPort: 10443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
      - name: borders-workflow-tasklist
        image: quay.io/ukhomeofficedigital/borders-workflow-tasklist:latest
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: {{ .KUBE_CPU_LIMIT }}
            memory: {{ .KUBE_MEMORY_LIMIT }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
        env:
        - name: REALM
          valueFrom:
            secretKeyRef:
              name: borders-workflow-tasklist
              key: auth-realm
        - name: AUTH_URL
          valueFrom:
            secretKeyRef:
              name: borders-workflow-tasklist
              key: auth-url
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: borders-workflow-tasklist
              key: client-id
      volumes:
      - name: bundle
        configMap:
          name: bundle
      - name: certs
        emptyDir: {}
