---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.NAME}}
  annotations:
    downscaler/uptime: {{.UPTIME}}
spec:
  selector:
    matchLabels:
      name: {{.NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        env:
        - name: PROXY_SERVICE_HOST
          value: "127.0.0.1"
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: LOG_FORMAT_NAME
          value: 'json'
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: STATSD_METRICS
          value: "FALSE"
        ports:
        - name: https
          containerPort: 10443
      - name: {{.NAME}}
        image: "quay.io/ukhomeofficedigital/cop-private-workflow-tasklist:{{.IMAGE_TAG}}"
        imagePullPolicy: Always
        env:
        - name: EXT_DOMAIN
          value: {{.EXT_DOMAIN}}
        - name: REPORTING_SERVICE_NAME
          value: {{.REPORTING_SERVER_NAME}}
        - name: REF_DATA_URL
          value: {{.REF_DATA_URL}}
        - name: FORM_IO_NAME
          value: {{.FORMIO_SERVER_NAME}}
        - name: WORKFLOW_NAME
          value: {{.WORKFLOW_SERVER_NAME}}
        - name: TRANSLATION_SERVICE_NAME
          value: {{.TRANSLATION_SERVER_NAME}}
        - name: FILE_UPLOAD_SERVER_NAME
          value: {{.FILE_UPLOAD_SERVER_NAME}}
        - name: UI_ENVIRONMENT
          value: {{.UI_ENVIRONMENT}}
        - name: UI_VERSION
          value: {{.UI_VERSION}}
        - name: AUTH_REALM
          value: {{.KEYCLOAK_REALM}}
        - name: AUTH_URL
          value: {{.KEYCLOAK_URL}}
        - name: AUTH_CLIENT_ID
          value: {{.NAME}}
        - name: AUTH_ACCESS_ROLE
          value: {{.KEYCLOAK_ROLE}}
        - name: AUTH_ACCESS_CONTACT
          value: {{.KEYCLOAK_CONTACT}}
        - name: PROTOCOL
          value: {{.PROTOCOL}}
        - name: FORMIO_SERVER_NAME
          value: {{.FORMIO_SERVER_NAME}}
        - name: REPORTING_SERVER_NAME
          value: {{.REPORTING_SERVER_NAME}}
        - name: TRANSLATION_SERVER_NAME
          value: {{.TRANSLATION_SERVER_NAME}}
        - name: WORKFLOW_SERVER_NAME
          value: {{.WORKFLOW_SERVER_NAME}}
        - name: OPERATIONAL_DATA_URL
          value: {{.OPERATIONAL_DATA_URL}}
        - name: REPORT_SERVICE_URL
          value: {{.PROTOCOL}}{{.REPORTING_SERVER_NAME}}.{{.EXT_DOMAIN}}
        - name: TRANSLATION_SERVICE_URL
          value: {{.PROTOCOL}}{{.TRANSLATION_SERVER_NAME}}.{{.EXT_DOMAIN}}
        - name: WORKFLOW_SERVICE_URL
          value: {{.PROTOCOL}}{{.WORKFLOW_SERVER_NAME}}.{{.EXT_DOMAIN}}
        securityContext:
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
