apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    stable.k8s.psg.io/kcm.class: default
  name: borders-workflow-tasklist
spec:
  rules:
   - host: {{ .DNS_NAME }}
     http:
      paths:
      - backend:
          serviceName: borders-workflow-tasklist
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{ .DNS_NAME }}
    secretName: tls-borders-workflow-tasklist