---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.WWW_NAME}}
spec:
  podSelector:
    matchLabels:
      name: {{.WWW_NAME}}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - protocol: TCP
      port: 10443
