---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: permit-ingress-tasklist
spec:
  podSelector:
    matchLabels:
      name: borders-workflow-tasklist
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
    ports:
    - protocol: TCP
      port: 10443