---
apiVersion: v1
data:
  1.conf: |
    location / {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "http://127.0.0.1:8080";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  2.conf: |
    location /api/platform-data/ {
        echo_read_request_body;
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        proxy_pass https://{{.OPERATIONAL_POSTGREST_NAME}}.{{.INT_DOMAIN}}/;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  3.conf: |
    location /ws/workflow {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "https://{{.WORKFLOW_SERVER_NAME}}.{{.INT_DOMAIN}}";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        add_header X-Frame-Options "";
        proxy_read_timeout 240s;
    }
  4.conf: |
    location /api/workflow {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "https://{{.WORKFLOW_SERVER_NAME}}.{{.INT_DOMAIN}}";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  5.conf: |
    location /rest/camunda {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "https://{{.WORKFLOW_SERVER_NAME}}.{{.INT_DOMAIN}}";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  6.conf: |
    location /api/form/ {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        proxy_pass https://{{.FORMIO_SERVER_NAME}}.{{.INT_DOMAIN}}/form/;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  7.conf: |
    location /api/translation {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "https://{{.TRANSLATION_SERVER_NAME}}.{{.INT_DOMAIN}}";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  8.conf: |
    location /api/reports {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "https://{{.REPORTING_SERVER_NAME}}.{{.INT_DOMAIN}}";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_hide_header X-XSS-Protection;
        proxy_hide_header X-Frame-Options;
    }
  9.conf: |
    location /reportspublic {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        set $proxy_address "https://{{.REPORTING_SERVER_NAME}}.{{.INT_DOMAIN}}";
        set $backend_upstream "$proxy_address";
        proxy_pass $backend_upstream;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_hide_header X-XSS-Protection;
        proxy_hide_header X-Frame-Options;
    }
  10.conf: |
    location /formio/ {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        proxy_pass https://{{.FORMIO_SERVER_NAME}}.{{.INT_DOMAIN}}/;
        proxy_redirect default;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_hide_header X-XSS-Protection;
        proxy_hide_header X-Frame-Options;
    }
  11.conf: |
    location /form/ {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        proxy_pass https://{{.FORMIO_SERVER_NAME}}.{{.INT_DOMAIN}};
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
  13.conf: |
    location /api/files {
        gzip off; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k;
        error_page 599 /nginx-proxy/599.shtml;
        proxy_pass https://{{.FILE_UPLOAD_SERVER_NAME}}.{{.INT_DOMAIN}}/files;
        proxy_redirect  off;
        proxy_intercept_errors on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Username "";
        proxy_set_header X-Real-IP $remote_addr;
    }
kind: ConfigMap
metadata:
  name: "{{.NAME}}"


