export const RESET = "RESET";
export const FIND_CASES_BY_KEY = "FIND_CASES_BY_KEY";
export const FIND_CASES_BY_KEY_SUCCESS = "FIND_CASES_BY_KEY_SUCCESS";
export const FIND_CASES_BY_KEY_FAILURE = "FIND_CASES_BY_KEY_FAILURE";
